const CATEGORIES = {
  core:     { color: '#a078ff', label: 'Core' },
  tool:     { color: '#50c8dc', label: 'Tools' },
  language: { color: '#ffb446', label: 'Languages' },
  concept:  { color: '#64dca0', label: 'Concepts' },
  project:  { color: '#ff6478', label: 'Projects' },
  resource: { color: '#dc82dc', label: 'Resources' },
};

const nodes = [
  { id: 'javascript', label: 'JavaScript', category: 'language' },
  { id: 'typescript', label: 'TypeScript', category: 'language' },
  { id: 'python', label: 'Python', category: 'language' },
  { id: 'rust', label: 'Rust', category: 'language' },
  { id: 'go', label: 'Go', category: 'language' },
  { id: 'html', label: 'HTML', category: 'language' },
  { id: 'css', label: 'CSS', category: 'language' },
  { id: 'sql', label: 'SQL', category: 'language' },

  { id: 'react', label: 'React', category: 'tool' },
  { id: 'vue', label: 'Vue', category: 'tool' },
  { id: 'svelte', label: 'Svelte', category: 'tool' },
  { id: 'nextjs', label: 'Next.js', category: 'tool' },
  { id: 'vite', label: 'Vite', category: 'tool' },
  { id: 'webpack', label: 'Webpack', category: 'tool' },
  { id: 'node', label: 'Node.js', category: 'tool' },
  { id: 'deno', label: 'Deno', category: 'tool' },
  { id: 'docker', label: 'Docker', category: 'tool' },
  { id: 'git', label: 'Git', category: 'tool' },
  { id: 'postgres', label: 'PostgreSQL', category: 'tool' },
  { id: 'redis', label: 'Redis', category: 'tool' },
  { id: 'graphql', label: 'GraphQL', category: 'tool' },
  { id: 'rest', label: 'REST APIs', category: 'tool' },
  { id: 'tailwind', label: 'Tailwind', category: 'tool' },
  { id: 'd3', label: 'D3.js', category: 'tool' },
  { id: 'threejs', label: 'Three.js', category: 'tool' },

  { id: 'fp', label: 'Functional Programming', category: 'concept' },
  { id: 'oop', label: 'OOP', category: 'concept' },
  { id: 'algorithms', label: 'Algorithms', category: 'concept' },
  { id: 'data-structures', label: 'Data Structures', category: 'concept' },
  { id: 'design-patterns', label: 'Design Patterns', category: 'concept' },
  { id: 'testing', label: 'Testing', category: 'concept' },
  { id: 'ci-cd', label: 'CI/CD', category: 'concept' },
  { id: 'microservices', label: 'Microservices', category: 'concept' },
  { id: 'serverless', label: 'Serverless', category: 'concept' },
  { id: 'auth', label: 'Authentication', category: 'concept' },
  { id: 'websockets', label: 'WebSockets', category: 'concept' },
  { id: 'state-mgmt', label: 'State Management', category: 'concept' },
  { id: 'accessibility', label: 'Accessibility', category: 'concept' },
  { id: 'perf', label: 'Performance', category: 'concept' },
  { id: 'security', label: 'Security', category: 'concept' },
  { id: 'concurrency', label: 'Concurrency', category: 'concept' },
  { id: 'types', label: 'Type Systems', category: 'concept' },
  { id: 'rendering', label: 'Rendering', category: 'concept' },

  { id: 'web', label: 'Web Development', category: 'core' },
  { id: 'backend', label: 'Backend', category: 'core' },
  { id: 'frontend', label: 'Frontend', category: 'core' },
  { id: 'devops', label: 'DevOps', category: 'core' },
  { id: 'databases', label: 'Databases', category: 'core' },
  { id: 'ai-ml', label: 'AI / ML', category: 'core' },
  { id: 'visualization', label: 'Data Viz', category: 'core' },

  { id: 'portfolio', label: 'Portfolio Site', category: 'project' },
  { id: 'saas', label: 'SaaS App', category: 'project' },
  { id: 'cli-tool', label: 'CLI Tool', category: 'project' },
  { id: 'mobile-app', label: 'Mobile App', category: 'project' },
  { id: 'api-service', label: 'API Service', category: 'project' },

  { id: 'mdn', label: 'MDN Docs', category: 'resource' },
  { id: 'stackoverflow', label: 'Stack Overflow', category: 'resource' },
  { id: 'github', label: 'GitHub', category: 'resource' },
];

const links = [
  { source: 'javascript', target: 'typescript' },
  { source: 'javascript', target: 'html' },
  { source: 'javascript', target: 'css' },
  { source: 'typescript', target: 'types' },
  { source: 'javascript', target: 'node' },
  { source: 'javascript', target: 'react' },
  { source: 'javascript', target: 'vue' },
  { source: 'javascript', target: 'svelte' },
  { source: 'javascript', target: 'd3' },
  { source: 'javascript', target: 'threejs' },
  { source: 'typescript', target: 'react' },
  { source: 'typescript', target: 'nextjs' },
  { source: 'python', target: 'ai-ml' },
  { source: 'python', target: 'backend' },
  { source: 'rust', target: 'concurrency' },
  { source: 'rust', target: 'perf' },
  { source: 'go', target: 'concurrency' },
  { source: 'go', target: 'backend' },
  { source: 'go', target: 'microservices' },
  { source: 'sql', target: 'databases' },
  { source: 'sql', target: 'postgres' },
  { source: 'react', target: 'nextjs' },
  { source: 'react', target: 'state-mgmt' },
  { source: 'react', target: 'frontend' },
  { source: 'vue', target: 'frontend' },
  { source: 'svelte', target: 'frontend' },
  { source: 'nextjs', target: 'frontend' },
  { source: 'nextjs', target: 'backend' },
  { source: 'nextjs', target: 'serverless' },
  { source: 'vite', target: 'frontend' },
  { source: 'vite', target: 'react' },
  { source: 'vite', target: 'vue' },
  { source: 'vite', target: 'svelte' },
  { source: 'webpack', target: 'vite' },
  { source: 'webpack', target: 'frontend' },
  { source: 'node', target: 'backend' },
  { source: 'node', target: 'deno' },
  { source: 'deno', target: 'typescript' },
  { source: 'docker', target: 'devops' },
  { source: 'docker', target: 'microservices' },
  { source: 'git', target: 'devops' },
  { source: 'git', target: 'ci-cd' },
  { source: 'git', target: 'github' },
  { source: 'postgres', target: 'databases' },
  { source: 'redis', target: 'databases' },
  { source: 'redis', target: 'perf' },
  { source: 'graphql', target: 'rest' },
  { source: 'graphql', target: 'backend' },
  { source: 'rest', target: 'backend' },
  { source: 'tailwind', target: 'css' },
  { source: 'tailwind', target: 'frontend' },
  { source: 'd3', target: 'visualization' },
  { source: 'threejs', target: 'visualization' },
  { source: 'threejs', target: 'rendering' },
  { source: 'fp', target: 'javascript' },
  { source: 'fp', target: 'rust' },
  { source: 'oop', target: 'design-patterns' },
  { source: 'oop', target: 'javascript' },
  { source: 'oop', target: 'python' },
  { source: 'algorithms', target: 'data-structures' },
  { source: 'algorithms', target: 'perf' },
  { source: 'design-patterns', target: 'backend' },
  { source: 'testing', target: 'ci-cd' },
  { source: 'testing', target: 'frontend' },
  { source: 'testing', target: 'backend' },
  { source: 'ci-cd', target: 'devops' },
  { source: 'ci-cd', target: 'docker' },
  { source: 'microservices', target: 'backend' },
  { source: 'serverless', target: 'backend' },
  { source: 'auth', target: 'security' },
  { source: 'auth', target: 'backend' },
  { source: 'websockets', target: 'node' },
  { source: 'websockets', target: 'backend' },
  { source: 'state-mgmt', target: 'frontend' },
  { source: 'accessibility', target: 'frontend' },
  { source: 'accessibility', target: 'html' },
  { source: 'perf', target: 'frontend' },
  { source: 'perf', target: 'backend' },
  { source: 'security', target: 'backend' },
  { source: 'rendering', target: 'frontend' },
  { source: 'rendering', target: 'perf' },
  { source: 'web', target: 'frontend' },
  { source: 'web', target: 'backend' },
  { source: 'frontend', target: 'html' },
  { source: 'frontend', target: 'css' },
  { source: 'frontend', target: 'javascript' },
  { source: 'backend', target: 'databases' },
  { source: 'devops', target: 'backend' },
  { source: 'visualization', target: 'frontend' },
  { source: 'ai-ml', target: 'algorithms' },
  { source: 'ai-ml', target: 'data-structures' },
  { source: 'portfolio', target: 'frontend' },
  { source: 'portfolio', target: 'react' },
  { source: 'portfolio', target: 'tailwind' },
  { source: 'saas', target: 'frontend' },
  { source: 'saas', target: 'backend' },
  { source: 'saas', target: 'auth' },
  { source: 'saas', target: 'postgres' },
  { source: 'cli-tool', target: 'rust' },
  { source: 'cli-tool', target: 'go' },
  { source: 'mobile-app', target: 'react' },
  { source: 'api-service', target: 'rest' },
  { source: 'api-service', target: 'graphql' },
  { source: 'api-service', target: 'node' },
  { source: 'mdn', target: 'javascript' },
  { source: 'mdn', target: 'html' },
  { source: 'mdn', target: 'css' },
  { source: 'stackoverflow', target: 'web' },
  { source: 'github', target: 'git' },
  { source: 'github', target: 'web' },
];

// Pre-compute connection counts
const connectionCount = {};
links.forEach((l) => {
  connectionCount[l.source] = (connectionCount[l.source] || 0) + 1;
  connectionCount[l.target] = (connectionCount[l.target] || 0) + 1;
});

nodes.forEach((n) => {
  n.connections = connectionCount[n.id] || 0;
  n.categoryData = CATEGORIES[n.category];
});

export { nodes, links, CATEGORIES };
